name: Build and Push
on:
  push:
    branches:
      - feature/sreedhar/mockapis
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.0.0' # Adjust the Node.js version to what you need
 
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }} -p    ${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }} --tenant ${{ secrets.SERVICE_PRINCIPAL_TENANT_ID }}
 
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_USERNAME}}
 
      # Steps for building and pushing Docker images
      - name: Build Docker image
        run: docker build -t crscphdev001.azurecr.io/scphdckrimg:${{ github.run_id }} .
 
      - name: Push Docker image to Azure Container Registry
        run: docker push crscphdev001.azurecr.io/scphdckrimg:${{ github.run_id }}
     # Deploy Docker image to Azure Function App
      - name: Deploy to Azure Function App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: funcscph-web-dev-001
          images: crscphdev001.azurecr.io/scphdckrimg:${{ github.run_id }}
